name: "mspecs-wp-plugin"
version: "3.9"

services:
  db:
    image: mysql:8.0.31
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ${WP_DATABASE_PATH:-./data/mysql}:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
    ports:
      - 33060:3306
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ${WP_API_PLUGIN_PATH:-../}:/var/www/html/wp-content/plugins/wp-api-plugin

