# This is a basic workflow to help you get started with Actions

name: Zip Dist

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events if tagged
  push:
    tags:
    - '*'
  pull_request:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'dist.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig *.phpdoc* phpdoc.dist.xml'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
